//! Decision probe for Team Rocket's Magmar's conditional-damage estimate.
//!
//! This deliberately enters the decision through `PlayerObservation::from_state` and
//! `Player::decision_fn`. The two candidates are legal stack actions generated by the
//! real Bouncy Body trigger, rather than hand-built alternatives.
//!
//! Independent local objective: allocate the forced Water Energy to the benched Pokemon
//! with the larger immediately ready attack against the public opposing Active. With no
//! Special Condition that is Starly (Pluck 20 versus Derisive Roasting 10). With Poison,
//! that is Team Rocket's Magmar (Derisive Roasting 60 versus Pluck 20). This objective is
//! intentionally tactical; it is not a claim of long-horizon game-optimal play.

use deckgym::{
    actions::{Action, SimpleAction},
    card_ids::CardId,
    models::{EnergyType, PlayedCard, StatusCondition},
    observation::{canonical_actions, PlayerObservation, RevealedKnowledge},
    players::{
        public_clock_effect_value_function, public_damage_value_function,
        public_effect_value_function, ExpectiMiniMaxPlayer, Player, ValueFunction,
    },
    test_support::{attack_action, get_initialized_game_with_board},
    Deck, State,
};
use rand::{rngs::StdRng, SeedableRng};

const MAGMAR_IDX: usize = 1;
const STARLY_IDX: usize = 2;

fn pending_bouncy_body_choice(poisoned: bool) -> (State, PlayerObservation, Vec<Action>, Deck) {
    let mut pikachu = PlayedCard::from_id(CardId::A1094Pikachu)
        .with_energy(vec![EnergyType::Lightning]);
    if poisoned {
        pikachu = pikachu.with_status_condition(StatusCondition::Poisoned);
    }

    let mut game = get_initialized_game_with_board(
        47,
        0,
        3,
        vec![pikachu],
        vec![
            PlayedCard::from_id(CardId::B1069Jellicent),
            PlayedCard::from_id(CardId::B4a006TeamRocketsMagmar),
            PlayedCard::from_id(CardId::A2132Starly),
        ],
    );

    // Eliminate own evolution potential and every hand/deck action from the comparison.
    // The board, pending choice, Energy, HP, damage and Special Conditions remain public.
    let mut state = game.get_state_clone();
    state.hands = [Vec::new(), Vec::new()];
    state.decks[0].cards.clear();
    state.decks[1].cards.clear();
    game.set_state(state);

    game.apply_action(&Action {
        actor: 0,
        action: attack_action(CardId::A1094Pikachu, 0),
        is_stack: false,
    });

    let pending = game.get_state_clone();
    let (actor, mut actions) = pending.generate_possible_actions();
    canonical_actions(&mut actions);
    assert_eq!(
        actor, 1,
        "Bouncy Body's choice must belong to Jellicent's owner"
    );
    assert_eq!(
        actions.len(),
        2,
        "fixture must expose exactly the two bench targets"
    );

    let mut targets: Vec<usize> = actions.iter().map(attach_target).collect();
    targets.sort_unstable();
    assert_eq!(targets, vec![MAGMAR_IDX, STARLY_IDX]);
    assert!(actions.iter().all(|action| action.is_stack));
    assert_eq!(pending.get_active(0).is_poisoned(), poisoned);

    let observation = PlayerObservation::from_state(
        &pending,
        actor,
        &RevealedKnowledge::default(),
    );
    assert_eq!(
        observation.visible_state().get_active(0).is_poisoned(),
        poisoned
    );
    assert_eq!(observation.visible_state().generate_possible_actions().1, actions);
    let deck = pending.decks[actor].clone();
    (pending, observation, actions, deck)
}

fn attach_target(action: &Action) -> usize {
    match &action.action {
        SimpleAction::Attach {
            attachments,
            is_turn_energy: false,
        } if attachments.len() == 1 && attachments[0].0 == 1
            && attachments[0].1 == EnergyType::Water => attachments[0].2,
        other => panic!("expected one Bouncy Body Water attachment, got {other:?}"),
    }
}

fn choose(
    observation: &PlayerObservation,
    actions: &[Action],
    deck: &Deck,
    value_function: ValueFunction,
    seed: u64,
) -> usize {
    let mut bot = ExpectiMiniMaxPlayer {
        deck: deck.clone(),
        max_depth: 1,
        write_debug_trees: false,
        value_function,
        opponent_ply: 0,
        consistent_horizon: false,
        soft_opponent: false,
    };
    let choice = bot.decision_fn(
        &mut StdRng::seed_from_u64(seed),
        observation,
        actions,
    );
    assert!(
        actions.contains(&choice),
        "bot must return one offered legal action"
    );
    attach_target(&choice)
}

fn label(target: usize) -> &'static str {
    match target {
        MAGMAR_IDX => "Team Rocket's Magmar",
        STARLY_IDX => "Starly",
        _ => "unexpected target",
    }
}

#[test]
fn effect_aware_bot_readies_the_stronger_attack_in_a_real_bouncy_body_choice() {
    for poisoned in [false, true] {
        let (_, observation, actions, deck) = pending_bouncy_body_choice(poisoned);

        // The raw-damage control retains its preference for Starly. The corrected f
        // choice must track the predeclared immediate-ready-damage objective.
        let d = choose(
            &observation,
            &actions,
            &deck,
            Box::new(public_damage_value_function),
            91,
        );
        let f = choose(
            &observation,
            &actions,
            &deck,
            Box::new(public_effect_value_function),
            91,
        );
        let k = choose(
            &observation,
            &actions,
            &deck,
            Box::new(public_clock_effect_value_function),
            91,
        );

        println!(
            "poisoned={poisoned}: d1={}, f1={}, k1={}",
            label(d),
            label(f),
            label(k),
        );

        assert_eq!(d, STARLY_IDX, "raw-damage control changed");
        assert_eq!(f, if poisoned { MAGMAR_IDX } else { STARLY_IDX });
        assert_eq!(k, if poisoned { MAGMAR_IDX } else { STARLY_IDX });

        // Independent tactical damage objective; no full-game optimality claim.
        let magmar_damage = 10 + if poisoned { 50 } else { 0 };
        let starly_damage = 20;
        assert_eq!(
            if magmar_damage > starly_damage {
                MAGMAR_IDX
            } else {
                STARLY_IDX
            },
            if poisoned { MAGMAR_IDX } else { STARLY_IDX },
        );
    }
}

#[test]
fn complete_magmar_energy_choice_hides_unknown_cards_and_deck_order() {
    use deckgym::database::get_card_by_enum;
    for poisoned in [false, true] {
        let (mut state, _, actions, _) = pending_bouncy_body_choice(poisoned);
        // Actor 1 knows this remaining multiset, but not its order. Neither deck
        // contains an evolution or any other fact that changes the ready-attack objective.
        state.decks[1].cards = vec![get_card_by_enum(CardId::PA001Potion),
            get_card_by_enum(CardId::PA002XSpeed), get_card_by_enum(CardId::PA005PokeBall)];
        state.decks[0].cards = state.decks[1].cards.clone();
        state.hands[0] = vec![get_card_by_enum(CardId::PA007ProfessorsResearch)];
        let knowledge = RevealedKnowledge::default();
        let base = PlayerObservation::from_state(&state, 1, &knowledge);
        for seed in [7, 47, 91] {
            let baseline = choose(&base, &actions, &state.decks[1], Box::new(public_effect_value_function), seed);
            assert_eq!(baseline, if poisoned { MAGMAR_IDX } else { STARLY_IDX });
            let k_baseline = choose(&base, &actions, &state.decks[1], Box::new(public_clock_effect_value_function), seed);
            assert_eq!(k_baseline, if poisoned { MAGMAR_IDX } else { STARLY_IDX });
            for shift in 0..3 {
                let mut changed = state.clone();
                changed.decks[1].cards.rotate_left(shift);
                changed.decks[0].cards.fill(get_card_by_enum(CardId::A1003Venusaur));
                changed.hands[0].fill(get_card_by_enum(CardId::PA006RedCard));
                let observation = PlayerObservation::from_state(&changed, 1, &knowledge);
                assert_eq!(base, observation);
                assert_eq!(baseline, choose(&observation, &actions, &changed.decks[1],
                    Box::new(public_effect_value_function), seed));
                assert_eq!(k_baseline, choose(&observation, &actions, &changed.decks[1],
                    Box::new(public_clock_effect_value_function), seed));
            }
        }
    }
}
